apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentmanager-deployment
  namespace: arha-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agentmanager
  template:
    metadata:
      labels:
        app: agentmanager
    spec:
      containers:
        - name: agentmanager
          image: hiro08081/agentmanager_refact:12
          #image: hiro08081/agentmanager:
          ports:
            - name: http
              containerPort: 8888
            - name: websocket
              containerPort: 50051

          command: ["/bin/bash", "-c"]
          args: 
            - |
              apt update && apt install -y nano procps
              sleep infinity
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: arha-logs-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: arha-node-type
                operator: In
                values:
                - controller-node
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"