apiVersion: v1
kind: Pod
metadata:
  name: pose-workergpu2-30510-3
  labels:
    app: pose
    monitor: ml_server
spec:
  runtimeClassName: nvidia
  shareProcessNamespace: true  # 啟用進程共享
  nodeSelector:
    kubernetes.io/hostname: workgpu

  containers:
  - name: pose
    image:  hiro08081/infer_server:9
    command: ["python", "main.py"]
    env:
    - name: SERVICE
      value: "pose"
    - name: GRPC_PORT
      value: "50052"
    - name: QUEUE_TIMEOUT
      value: "3"
    readinessProbe:
      grpc:
        port: 50052
      initialDelaySeconds: 5
      periodSeconds: 5
    ports:
    - containerPort: 50052
      hostPort: 30510
    - containerPort: 8001
      name: http-metrics
    resources:
      limits:
        nvidia.com/gpu: 1
