apiVersion: v1
kind: Service
metadata:
  name: agentmanager-service
  namespace: {{ include "agentmanager.namespace" . }}
spec:
  type: NodePort
  selector:
    app: agentmanager
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      nodePort: {{ .Values.service.httpNodePort }}
    - name: websocket
      port: {{ .Values.service.websocketPort }}
      targetPort: {{ .Values.service.websocketPort }}
      nodePort: {{ .Values.service.websocketNodePort }}
