# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pose.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npose.proto\x12\x04pose\"\"\n\x0c\x46rameRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\"\n\rFrameResponse\x12\x11\n\tskeletons\x18\x01 \x01(\t2B\n\x06Mirror\x12\x38\n\rSkeletonFrame\x12\x12.pose.FrameRequest\x1a\x13.pose.FrameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=20
  _globals['_FRAMEREQUEST']._serialized_end=54
  _globals['_FRAMERESPONSE']._serialized_start=56
  _globals['_FRAMERESPONSE']._serialized_end=90
  _globals['_MIRROR']._serialized_start=92
  _globals['_MIRROR']._serialized_end=158
# @@protoc_insertion_point(module_scope)
